// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class Comercio
{
    public int id { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public int? telefono { get; set; }

    public string horario { get; set; }

    public string web { get; set; }

    public string descripcion { get; set; }

    public string nombreimagen { get; set; }

    public string provincia { get; set; }

    public string contraseña { get; set; }

    public string mail { get; set; }

    public string instagram { get; set; }

    public string facebook { get; set; }

    public string latitud { get; set; }

    public string longitud { get; set; }

    public double valoracionpromedio { get; set; }
    public virtual ICollection<Usuario> idusuario { get; set; } = new List<Usuario>();
    public virtual ICollection<Tipo> tipo_id { get; set; } = new List<Tipo>();

    public virtual ICollection<Reseña> reseñas { get; set; } = new List<Reseña>();
    public virtual ICollection<Anuncio> idcomercio { get; set; } = new List<Anuncio>();

}