// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Imagen
{
    public int id { get; set; }

    public byte[] image { get; set; }

    public string nombre { get; set; }
}