// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class Reseña
{
    public int usuario { get; set; }
    public int comercio { get; set; }
    public string titulo { get; set; }
    public string descripcion { get; set; }
    public int puntuacion { get; set; }
    public string nombreimagen { get; set;}
}