// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Tipo
{
    public int id { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Comercio> comercio_id { get; set; } = new List<Comercio>();
}