// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Usuario
{
    public int id { get; set; }

    public string nombre { get; set; }

    public string nickname { get; set; }

    public int? telefono { get; set; }

    public string nombreimagen { get; set; }

    public string contraseña { get; set; }

    public string mail { get; set; }

    public bool? estado { get; set; }

    public virtual ICollection<Comercio> idcomercio { get; set; } = new List<Comercio>();

    public virtual ICollection<Usuario> idseguido { get; set; } = new List<Usuario>();

    public virtual ICollection<Usuario> idseguidor { get; set; } = new List<Usuario>();
    public virtual ICollection<Reseña> reseñas { get; set; } = new List<Reseña>();

}