// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class Anuncio
{
    public int Id { get; set; }
    public int IdComercio { get; set; }
    public DateTime Fecha { get; set; }
    public string Titulo { get; set; }
    public string Descripcion { get; set; }
    public string NombreImagenes { get; set; }
    public string Tipo { get; set; }
    public Comercio Comercio { get; set; }
}