// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class Comercio
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public int? Telefono { get; set; }

    public string Horario { get; set; }

    public string Web { get; set; }

    public string Descripcion { get; set; }

    public int? ImagenId { get; set; }

    public string Provincia { get; set; }

    public string Contraseña { get; set; }

    public string Mail { get; set; }

    public string Instagram { get; set; }

    public string Facebook { get; set; }

    public virtual Imagen Imagen { get; set; }
    [JsonIgnore]
    public virtual ICollection<Usuario> IdUsuario { get; set; } = new List<Usuario>();

    public virtual ICollection<Tipo> Tipo { get; set; } = new List<Tipo>();
}