// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Imagen
{
    public int Id { get; set; }

    public byte[] ImagenReducidad { get; set; }

    public string Tipo { get; set; }

    public byte[] ImagenGrande { get; set; }

    public virtual Usuario Id1 { get; set; }

    public virtual Comercio IdNavigation { get; set; }
}