// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Models
{
    public partial interface IPropBDContextProcedures
    {
        Task<List<mostarProductosResult>> mostarProductosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
