// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string NickName { get; set; }

    public int? Telefono { get; set; }

    public int? ImagenId { get; set; }

    public string Contraseña { get; set; }

    public string Mail { get; set; }

    public bool? Estado { get; set; }

    public virtual Imagen Imagen { get; set; }

    public virtual ICollection<Comercio> IdComercio { get; set; } = new List<Comercio>();

    public virtual ICollection<Usuario> IdSeguido { get; set; } = new List<Usuario>();

    public virtual ICollection<Usuario> IdSeguidor { get; set; } = new List<Usuario>();
}